# Generated by Django 3.2.5 on 2021-10-26 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211018_0556'),
        ('api', '0016_entity_recognition'),
    ]

    operations = [
    ]
