# Generated by Django 3.2.5 on 2021-11-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_example_uuid'),
        ('api', '0017_merge_0016_auto_20211018_0556_0016_entity_recognition'),
    ]

    operations = [
    ]
