# Generated by Django 3.2.9 on 2021-12-03 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_merge_20211110_1607'),
        ('api', '0019_auto_20211124_0506'),
    ]

    operations = [
    ]
