# Generated by Django 3.2.12 on 2022-02-23 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_polymorphic_ctype'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityLinkingProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projects.project')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('projects.project',),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'document classification'), ('EntityLinking', 'entity linking'), ('SequenceLabeling', 'sequence labeling'), ('Seq2seq', 'sequence to sequence'), ('IntentDetectionAndSlotFilling', 'intent detection and slot filling'), ('Speech2text', 'speech to text'), ('ImageClassification', 'image classification')], max_length=30),
        ),
    ]
