# Generated by Django 3.2.12 on 2022-03-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20220223_1424'),
        ('projects', '0004_sequencelabelingproject_use_relation'),
    ]

    operations = [
    ]
