# Generated by Django 3.2.12 on 2022-02-23 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0002_alter_example_project'),
        ('labels', '0005_alter_relation_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitySpan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prob', models.FloatField(default=0.0)),
                ('manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ent_id', models.TextField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entityspans', to='examples.example')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='entityspan',
            constraint=models.CheckConstraint(check=models.Q(('start_offset__gte', 0)), name='startOffset>=0'),
        ),
        migrations.AddConstraint(
            model_name='entityspan',
            constraint=models.CheckConstraint(check=models.Q(('end_offset__gte', 0)), name='endOffset>=0'),
        ),
        migrations.AddConstraint(
            model_name='entityspan',
            constraint=models.CheckConstraint(check=models.Q(('start_offset__lt', django.db.models.expressions.F('end_offset'))), name='start<end'),
        ),
    ]
