# Generated by Django 3.2.12 on 2022-03-07 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0006_auto_20220223_1424'),
        ('labels', '0011_remove_relation_direction'),
    ]

    operations = [
    ]
