# Generated by Django 3.2.9 on 2022-05-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0012_merge_20220307_1344'),
        ('labels', '0014_remove_uuid_null'),
    ]

    operations = [
    ]
