# Generated by Django 3.2.9 on 2022-06-01 11:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0015_merge_0012_merge_20220307_1344_0014_remove_uuid_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityspan',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
